# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /media/ubuntu-gnome/_home/home2/0Desktop/1090b/4/cmake/bin/cmake

# The command to remove a file.
RM = /media/ubuntu-gnome/_home/home2/0Desktop/1090b/4/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu-gnome/qwtq

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu-gnome/qwtq

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/media/ubuntu-gnome/_home/home2/0Desktop/1090b/4/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/media/ubuntu-gnome/_home/home2/0Desktop/1090b/4/cmake/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu-gnome/qwtq/CMakeFiles /home/ubuntu-gnome/qwtq/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu-gnome/qwtq/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qwtq

# Build rule for target.
qwtq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qwtq
.PHONY : qwtq

# fast build rule for target.
qwtq/fast:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/build
.PHONY : qwtq/fast

#=============================================================================
# Target rules for targets named qwtq_autogen

# Build rule for target.
qwtq_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qwtq_autogen
.PHONY : qwtq_autogen

# fast build rule for target.
qwtq_autogen/fast:
	$(MAKE) -f CMakeFiles/qwtq_autogen.dir/build.make CMakeFiles/qwtq_autogen.dir/build
.PHONY : qwtq_autogen/fast

answer.o: answer.cpp.o

.PHONY : answer.o

# target to build an object file
answer.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/answer.cpp.o
.PHONY : answer.cpp.o

answer.i: answer.cpp.i

.PHONY : answer.i

# target to preprocess a source file
answer.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/answer.cpp.i
.PHONY : answer.cpp.i

answer.s: answer.cpp.s

.PHONY : answer.s

# target to generate assembly for a file
answer.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/answer.cpp.s
.PHONY : answer.cpp.s

ev3/expression.o: ev3/expression.cpp.o

.PHONY : ev3/expression.o

# target to build an object file
ev3/expression.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/expression.cpp.o
.PHONY : ev3/expression.cpp.o

ev3/expression.i: ev3/expression.cpp.i

.PHONY : ev3/expression.i

# target to preprocess a source file
ev3/expression.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/expression.cpp.i
.PHONY : ev3/expression.cpp.i

ev3/expression.s: ev3/expression.cpp.s

.PHONY : ev3/expression.s

# target to generate assembly for a file
ev3/expression.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/expression.cpp.s
.PHONY : ev3/expression.cpp.s

ev3/operand.o: ev3/operand.cpp.o

.PHONY : ev3/operand.o

# target to build an object file
ev3/operand.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/operand.cpp.o
.PHONY : ev3/operand.cpp.o

ev3/operand.i: ev3/operand.cpp.i

.PHONY : ev3/operand.i

# target to preprocess a source file
ev3/operand.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/operand.cpp.i
.PHONY : ev3/operand.cpp.i

ev3/operand.s: ev3/operand.cpp.s

.PHONY : ev3/operand.s

# target to generate assembly for a file
ev3/operand.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/operand.cpp.s
.PHONY : ev3/operand.cpp.s

ev3/parser.o: ev3/parser.cpp.o

.PHONY : ev3/parser.o

# target to build an object file
ev3/parser.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/parser.cpp.o
.PHONY : ev3/parser.cpp.o

ev3/parser.i: ev3/parser.cpp.i

.PHONY : ev3/parser.i

# target to preprocess a source file
ev3/parser.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/parser.cpp.i
.PHONY : ev3/parser.cpp.i

ev3/parser.s: ev3/parser.cpp.s

.PHONY : ev3/parser.s

# target to generate assembly for a file
ev3/parser.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/ev3/parser.cpp.s
.PHONY : ev3/parser.cpp.s

formulaview.o: formulaview.cpp.o

.PHONY : formulaview.o

# target to build an object file
formulaview.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/formulaview.cpp.o
.PHONY : formulaview.cpp.o

formulaview.i: formulaview.cpp.i

.PHONY : formulaview.i

# target to preprocess a source file
formulaview.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/formulaview.cpp.i
.PHONY : formulaview.cpp.i

formulaview.s: formulaview.cpp.s

.PHONY : formulaview.s

# target to generate assembly for a file
formulaview.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/formulaview.cpp.s
.PHONY : formulaview.cpp.s

fraction.o: fraction.cpp.o

.PHONY : fraction.o

# target to build an object file
fraction.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/fraction.cpp.o
.PHONY : fraction.cpp.o

fraction.i: fraction.cpp.i

.PHONY : fraction.i

# target to preprocess a source file
fraction.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/fraction.cpp.i
.PHONY : fraction.cpp.i

fraction.s: fraction.cpp.s

.PHONY : fraction.s

# target to generate assembly for a file
fraction.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/fraction.cpp.s
.PHONY : fraction.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

qrc_completer.o: qrc_completer.cpp.o

.PHONY : qrc_completer.o

# target to build an object file
qrc_completer.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qrc_completer.cpp.o
.PHONY : qrc_completer.cpp.o

qrc_completer.i: qrc_completer.cpp.i

.PHONY : qrc_completer.i

# target to preprocess a source file
qrc_completer.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qrc_completer.cpp.i
.PHONY : qrc_completer.cpp.i

qrc_completer.s: qrc_completer.cpp.s

.PHONY : qrc_completer.s

# target to generate assembly for a file
qrc_completer.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qrc_completer.cpp.s
.PHONY : qrc_completer.cpp.s

qwt_mathml_text_engine.o: qwt_mathml_text_engine.cpp.o

.PHONY : qwt_mathml_text_engine.o

# target to build an object file
qwt_mathml_text_engine.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mathml_text_engine.cpp.o
.PHONY : qwt_mathml_text_engine.cpp.o

qwt_mathml_text_engine.i: qwt_mathml_text_engine.cpp.i

.PHONY : qwt_mathml_text_engine.i

# target to preprocess a source file
qwt_mathml_text_engine.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mathml_text_engine.cpp.i
.PHONY : qwt_mathml_text_engine.cpp.i

qwt_mathml_text_engine.s: qwt_mathml_text_engine.cpp.s

.PHONY : qwt_mathml_text_engine.s

# target to generate assembly for a file
qwt_mathml_text_engine.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mathml_text_engine.cpp.s
.PHONY : qwt_mathml_text_engine.cpp.s

qwt_mml_document.o: qwt_mml_document.cpp.o

.PHONY : qwt_mml_document.o

# target to build an object file
qwt_mml_document.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_document.cpp.o
.PHONY : qwt_mml_document.cpp.o

qwt_mml_document.i: qwt_mml_document.cpp.i

.PHONY : qwt_mml_document.i

# target to preprocess a source file
qwt_mml_document.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_document.cpp.i
.PHONY : qwt_mml_document.cpp.i

qwt_mml_document.s: qwt_mml_document.cpp.s

.PHONY : qwt_mml_document.s

# target to generate assembly for a file
qwt_mml_document.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_document.cpp.s
.PHONY : qwt_mml_document.cpp.s

qwt_mml_entity_table.o: qwt_mml_entity_table.cpp.o

.PHONY : qwt_mml_entity_table.o

# target to build an object file
qwt_mml_entity_table.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_entity_table.cpp.o
.PHONY : qwt_mml_entity_table.cpp.o

qwt_mml_entity_table.i: qwt_mml_entity_table.cpp.i

.PHONY : qwt_mml_entity_table.i

# target to preprocess a source file
qwt_mml_entity_table.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_entity_table.cpp.i
.PHONY : qwt_mml_entity_table.cpp.i

qwt_mml_entity_table.s: qwt_mml_entity_table.cpp.s

.PHONY : qwt_mml_entity_table.s

# target to generate assembly for a file
qwt_mml_entity_table.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwt_mml_entity_table.cpp.s
.PHONY : qwt_mml_entity_table.cpp.s

qwtq_autogen/mocs_compilation.o: qwtq_autogen/mocs_compilation.cpp.o

.PHONY : qwtq_autogen/mocs_compilation.o

# target to build an object file
qwtq_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwtq_autogen/mocs_compilation.cpp.o
.PHONY : qwtq_autogen/mocs_compilation.cpp.o

qwtq_autogen/mocs_compilation.i: qwtq_autogen/mocs_compilation.cpp.i

.PHONY : qwtq_autogen/mocs_compilation.i

# target to preprocess a source file
qwtq_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwtq_autogen/mocs_compilation.cpp.i
.PHONY : qwtq_autogen/mocs_compilation.cpp.i

qwtq_autogen/mocs_compilation.s: qwtq_autogen/mocs_compilation.cpp.s

.PHONY : qwtq_autogen/mocs_compilation.s

# target to generate assembly for a file
qwtq_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/qwtq_autogen/mocs_compilation.cpp.s
.PHONY : qwtq_autogen/mocs_compilation.cpp.s

remap.o: remap.cpp.o

.PHONY : remap.o

# target to build an object file
remap.cpp.o:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/remap.cpp.o
.PHONY : remap.cpp.o

remap.i: remap.cpp.i

.PHONY : remap.i

# target to preprocess a source file
remap.cpp.i:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/remap.cpp.i
.PHONY : remap.cpp.i

remap.s: remap.cpp.s

.PHONY : remap.s

# target to generate assembly for a file
remap.cpp.s:
	$(MAKE) -f CMakeFiles/qwtq.dir/build.make CMakeFiles/qwtq.dir/remap.cpp.s
.PHONY : remap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... qwtq"
	@echo "... qwtq_autogen"
	@echo "... answer.o"
	@echo "... answer.i"
	@echo "... answer.s"
	@echo "... ev3/expression.o"
	@echo "... ev3/expression.i"
	@echo "... ev3/expression.s"
	@echo "... ev3/operand.o"
	@echo "... ev3/operand.i"
	@echo "... ev3/operand.s"
	@echo "... ev3/parser.o"
	@echo "... ev3/parser.i"
	@echo "... ev3/parser.s"
	@echo "... formulaview.o"
	@echo "... formulaview.i"
	@echo "... formulaview.s"
	@echo "... fraction.o"
	@echo "... fraction.i"
	@echo "... fraction.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... qrc_completer.o"
	@echo "... qrc_completer.i"
	@echo "... qrc_completer.s"
	@echo "... qwt_mathml_text_engine.o"
	@echo "... qwt_mathml_text_engine.i"
	@echo "... qwt_mathml_text_engine.s"
	@echo "... qwt_mml_document.o"
	@echo "... qwt_mml_document.i"
	@echo "... qwt_mml_document.s"
	@echo "... qwt_mml_entity_table.o"
	@echo "... qwt_mml_entity_table.i"
	@echo "... qwt_mml_entity_table.s"
	@echo "... qwtq_autogen/mocs_compilation.o"
	@echo "... qwtq_autogen/mocs_compilation.i"
	@echo "... qwtq_autogen/mocs_compilation.s"
	@echo "... remap.o"
	@echo "... remap.i"
	@echo "... remap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

